apiVersion: v1
kind: Service
metadata:
  name: inventory-tracker-service
spec:
  selector:
    app: inventory-tracker-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP